<?php
/**
 * ResetPasswordRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LifeHub\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResetPasswordRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ResetPasswordRequest
 * @package     LifeHub\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResetPasswordRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResetPasswordRequest"
     */
    public function testResetPasswordRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "password_confirmation"
     */
    public function testPropertyPasswordConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
