<?php
/**
 * TwoFactorCodeRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LifeHub\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TwoFactorCodeRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TwoFactorCodeRequest
 * @package     LifeHub\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TwoFactorCodeRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TwoFactorCodeRequest"
     */
    public function testTwoFactorCodeRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "two_factor_code"
     */
    public function testPropertyTwoFactorCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
