<?php
/**
 * V1DashboardPinsUpdate200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LifeHub\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1DashboardPinsUpdate200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description V1DashboardPinsUpdate200Response
 * @package     LifeHub\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1DashboardPinsUpdate200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1DashboardPinsUpdate200Response"
     */
    public function testV1DashboardPinsUpdate200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
