services:
  cache:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - project_network
    volumes:
      - cache:/data

  database:
    image: mysql
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - project_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8330:80"
    environment:
      - PMA_HOST=database
      - PMA_POST=3306
    networks:
      - project_network

  typesense:
    image: typesense/typesense:27.1
    container_name: typesense
    restart: unless-stopped
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - GLOG_minloglevel=1
    ports:
      - "8108:8108"
    volumes:
      - search:/data
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  cache:
  database:
  search:
