services:
  cache:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - project_network
    volumes:
      - cache:/data

  database:
    image: postgres:16.11-alpine3.22
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "log_statement=none", "-c", "log_min_duration_statement=1000", "-c", "log_connections=on", "-c", "log_disconnections=on" ]
    user: "70:70" # Postgres user
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER:-postgres}" -d "$${POSTGRES_DB:-postgres}" -h localhost || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    stop_grace_period: 120s
    networks:
      - project_network

  typesense:
    image: typesense/typesense:27.1
    container_name: typesense
    restart: unless-stopped
    volumes:
      - search:/data
    ports:
      - "8108:8108"
    networks:
      - project_network
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - GLOG_minloglevel=1

networks:
  project_network:
    driver: bridge

volumes:
  cache:
    driver: local
  database:
    driver: local
  search:
    driver: local
