<?php
/**
 * AuthApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LifeHub\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LifeHub\ApiClient\ApiException;
use LifeHub\ApiClient\Configuration;
use LifeHub\ApiClient\FormDataProcessor;
use LifeHub\ApiClient\HeaderSelector;
use LifeHub\ApiClient\ObjectSerializer;

/**
 * AuthApi Class Doc Comment
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1Login' => [
            'application/json',
        ],
        'v1LoginValidate' => [
            'application/json',
        ],
        'v1Logout' => [
            'application/json',
        ],
        'v1Me' => [
            'application/json',
        ],
        'v1PasswordEmail' => [
            'application/json',
        ],
        'v1PasswordReset' => [
            'application/json',
        ],
        'v1Register' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1Login
     *
     * @param  \LifeHub\ApiClient\Model\LoginRequest $login_request login_request (required)
     * @param  string[]|null $fields_users fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Login'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\V1Login203Response|\LifeHub\ApiClient\Model\V1Login401Response|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1Login($login_request, $fields_users = null, string $contentType = self::contentTypes['v1Login'][0])
    {
        list($response) = $this->v1LoginWithHttpInfo($login_request, $fields_users, $contentType);
        return $response;
    }

    /**
     * Operation v1LoginWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\LoginRequest $login_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Login'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\V1Login203Response|\LifeHub\ApiClient\Model\V1Login401Response|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LoginWithHttpInfo($login_request, $fields_users = null, string $contentType = self::contentTypes['v1Login'][0])
    {
        $request = $this->v1LoginRequest($login_request, $fields_users, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $request,
                        $response,
                    );
                case 203:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Login203Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Login401Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Register200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 203:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Login203Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Login401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1LoginAsync
     *
     * @param  \LifeHub\ApiClient\Model\LoginRequest $login_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LoginAsync($login_request, $fields_users = null, string $contentType = self::contentTypes['v1Login'][0])
    {
        return $this->v1LoginAsyncWithHttpInfo($login_request, $fields_users, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LoginAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\LoginRequest $login_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LoginAsyncWithHttpInfo($login_request, $fields_users = null, string $contentType = self::contentTypes['v1Login'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Register200Response';
        $request = $this->v1LoginRequest($login_request, $fields_users, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Login'
     *
     * @param  \LifeHub\ApiClient\Model\LoginRequest $login_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LoginRequest($login_request, $fields_users = null, string $contentType = self::contentTypes['v1Login'][0])
    {

        // verify the required parameter 'login_request' is set
        if ($login_request === null || (is_array($login_request) && count($login_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $login_request when calling v1Login'
            );
        }



        $resourcePath = '/v1/login';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_users,
            'fields[users]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($login_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($login_request));
            } else {
                $httpBody = $login_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1LoginValidate
     *
     * @param  \LifeHub\ApiClient\Model\TwoFactorCodeRequest $two_factor_code_request two_factor_code_request (required)
     * @param  string[]|null $fields_users fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LoginValidate'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1LoginValidate401Response|\LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1LoginValidate($two_factor_code_request, $fields_users = null, string $contentType = self::contentTypes['v1LoginValidate'][0])
    {
        list($response) = $this->v1LoginValidateWithHttpInfo($two_factor_code_request, $fields_users, $contentType);
        return $response;
    }

    /**
     * Operation v1LoginValidateWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\TwoFactorCodeRequest $two_factor_code_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LoginValidate'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1LoginValidate401Response|\LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LoginValidateWithHttpInfo($two_factor_code_request, $fields_users = null, string $contentType = self::contentTypes['v1LoginValidate'][0])
    {
        $request = $this->v1LoginValidateRequest($two_factor_code_request, $fields_users, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1LoginValidate401Response',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Register200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1LoginValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1LoginValidateAsync
     *
     * @param  \LifeHub\ApiClient\Model\TwoFactorCodeRequest $two_factor_code_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LoginValidate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LoginValidateAsync($two_factor_code_request, $fields_users = null, string $contentType = self::contentTypes['v1LoginValidate'][0])
    {
        return $this->v1LoginValidateAsyncWithHttpInfo($two_factor_code_request, $fields_users, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LoginValidateAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\TwoFactorCodeRequest $two_factor_code_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LoginValidate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LoginValidateAsyncWithHttpInfo($two_factor_code_request, $fields_users = null, string $contentType = self::contentTypes['v1LoginValidate'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Register200Response';
        $request = $this->v1LoginValidateRequest($two_factor_code_request, $fields_users, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1LoginValidate'
     *
     * @param  \LifeHub\ApiClient\Model\TwoFactorCodeRequest $two_factor_code_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LoginValidate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LoginValidateRequest($two_factor_code_request, $fields_users = null, string $contentType = self::contentTypes['v1LoginValidate'][0])
    {

        // verify the required parameter 'two_factor_code_request' is set
        if ($two_factor_code_request === null || (is_array($two_factor_code_request) && count($two_factor_code_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $two_factor_code_request when calling v1LoginValidate'
            );
        }



        $resourcePath = '/v1/login/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_users,
            'fields[users]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($two_factor_code_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($two_factor_code_request));
            } else {
                $httpBody = $two_factor_code_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1Logout
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Logout'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1Logout200Response|\LifeHub\ApiClient\Model\InlineObject1
     */
    public function v1Logout(string $contentType = self::contentTypes['v1Logout'][0])
    {
        list($response) = $this->v1LogoutWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation v1LogoutWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Logout'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1Logout200Response|\LifeHub\ApiClient\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LogoutWithHttpInfo(string $contentType = self::contentTypes['v1Logout'][0])
    {
        $request = $this->v1LogoutRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Logout200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Logout200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Logout200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1LogoutAsync
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LogoutAsync(string $contentType = self::contentTypes['v1Logout'][0])
    {
        return $this->v1LogoutAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LogoutAsyncWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LogoutAsyncWithHttpInfo(string $contentType = self::contentTypes['v1Logout'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Logout200Response';
        $request = $this->v1LogoutRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Logout'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LogoutRequest(string $contentType = self::contentTypes['v1Logout'][0])
    {


        $resourcePath = '/v1/logout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1Me
     *
     * @param  string[]|null $fields_users fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Me'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject1
     */
    public function v1Me($fields_users = null, string $contentType = self::contentTypes['v1Me'][0])
    {
        list($response) = $this->v1MeWithHttpInfo($fields_users, $contentType);
        return $response;
    }

    /**
     * Operation v1MeWithHttpInfo
     *
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Me'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1MeWithHttpInfo($fields_users = null, string $contentType = self::contentTypes['v1Me'][0])
    {
        $request = $this->v1MeRequest($fields_users, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Register200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1MeAsync
     *
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Me'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MeAsync($fields_users = null, string $contentType = self::contentTypes['v1Me'][0])
    {
        return $this->v1MeAsyncWithHttpInfo($fields_users, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1MeAsyncWithHttpInfo
     *
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Me'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MeAsyncWithHttpInfo($fields_users = null, string $contentType = self::contentTypes['v1Me'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Register200Response';
        $request = $this->v1MeRequest($fields_users, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Me'
     *
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Me'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1MeRequest($fields_users = null, string $contentType = self::contentTypes['v1Me'][0])
    {



        $resourcePath = '/v1/me';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_users,
            'fields[users]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1PasswordEmail
     *
     * @param  \LifeHub\ApiClient\Model\ForgotPasswordRequest $forgot_password_request forgot_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordEmail'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1PasswordEmail500Response|\LifeHub\ApiClient\Model\V1PasswordEmail200Response|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1PasswordEmail($forgot_password_request, string $contentType = self::contentTypes['v1PasswordEmail'][0])
    {
        list($response) = $this->v1PasswordEmailWithHttpInfo($forgot_password_request, $contentType);
        return $response;
    }

    /**
     * Operation v1PasswordEmailWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\ForgotPasswordRequest $forgot_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordEmail'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1PasswordEmail500Response|\LifeHub\ApiClient\Model\V1PasswordEmail200Response|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1PasswordEmailWithHttpInfo($forgot_password_request, string $contentType = self::contentTypes['v1PasswordEmail'][0])
    {
        $request = $this->v1PasswordEmailRequest($forgot_password_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 500:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1PasswordEmail500Response',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1PasswordEmail200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1PasswordEmail200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1PasswordEmail500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1PasswordEmail200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1PasswordEmailAsync
     *
     * @param  \LifeHub\ApiClient\Model\ForgotPasswordRequest $forgot_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PasswordEmailAsync($forgot_password_request, string $contentType = self::contentTypes['v1PasswordEmail'][0])
    {
        return $this->v1PasswordEmailAsyncWithHttpInfo($forgot_password_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1PasswordEmailAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\ForgotPasswordRequest $forgot_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PasswordEmailAsyncWithHttpInfo($forgot_password_request, string $contentType = self::contentTypes['v1PasswordEmail'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1PasswordEmail200Response';
        $request = $this->v1PasswordEmailRequest($forgot_password_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1PasswordEmail'
     *
     * @param  \LifeHub\ApiClient\Model\ForgotPasswordRequest $forgot_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1PasswordEmailRequest($forgot_password_request, string $contentType = self::contentTypes['v1PasswordEmail'][0])
    {

        // verify the required parameter 'forgot_password_request' is set
        if ($forgot_password_request === null || (is_array($forgot_password_request) && count($forgot_password_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $forgot_password_request when calling v1PasswordEmail'
            );
        }


        $resourcePath = '/v1/forgot-password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($forgot_password_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($forgot_password_request));
            } else {
                $httpBody = $forgot_password_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1PasswordReset
     *
     * @param  \LifeHub\ApiClient\Model\ResetPasswordRequest $reset_password_request reset_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordReset'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1PasswordReset400Response|\LifeHub\ApiClient\Model\V1PasswordReset200Response|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1PasswordReset($reset_password_request, string $contentType = self::contentTypes['v1PasswordReset'][0])
    {
        list($response) = $this->v1PasswordResetWithHttpInfo($reset_password_request, $contentType);
        return $response;
    }

    /**
     * Operation v1PasswordResetWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\ResetPasswordRequest $reset_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordReset'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1PasswordReset400Response|\LifeHub\ApiClient\Model\V1PasswordReset200Response|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1PasswordResetWithHttpInfo($reset_password_request, string $contentType = self::contentTypes['v1PasswordReset'][0])
    {
        $request = $this->v1PasswordResetRequest($reset_password_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1PasswordReset400Response',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1PasswordReset200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1PasswordReset200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1PasswordReset400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1PasswordReset200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1PasswordResetAsync
     *
     * @param  \LifeHub\ApiClient\Model\ResetPasswordRequest $reset_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordReset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PasswordResetAsync($reset_password_request, string $contentType = self::contentTypes['v1PasswordReset'][0])
    {
        return $this->v1PasswordResetAsyncWithHttpInfo($reset_password_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1PasswordResetAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\ResetPasswordRequest $reset_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordReset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PasswordResetAsyncWithHttpInfo($reset_password_request, string $contentType = self::contentTypes['v1PasswordReset'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1PasswordReset200Response';
        $request = $this->v1PasswordResetRequest($reset_password_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1PasswordReset'
     *
     * @param  \LifeHub\ApiClient\Model\ResetPasswordRequest $reset_password_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PasswordReset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1PasswordResetRequest($reset_password_request, string $contentType = self::contentTypes['v1PasswordReset'][0])
    {

        // verify the required parameter 'reset_password_request' is set
        if ($reset_password_request === null || (is_array($reset_password_request) && count($reset_password_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $reset_password_request when calling v1PasswordReset'
            );
        }


        $resourcePath = '/v1/reset-password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($reset_password_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($reset_password_request));
            } else {
                $httpBody = $reset_password_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1Register
     *
     * @param  \LifeHub\ApiClient\Model\RegisterRequest $register_request register_request (required)
     * @param  string[]|null $fields_users fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Register'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1Register($register_request, $fields_users = null, string $contentType = self::contentTypes['v1Register'][0])
    {
        list($response) = $this->v1RegisterWithHttpInfo($register_request, $fields_users, $contentType);
        return $response;
    }

    /**
     * Operation v1RegisterWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\RegisterRequest $register_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Register'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1Register200Response|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1RegisterWithHttpInfo($register_request, $fields_users = null, string $contentType = self::contentTypes['v1Register'][0])
    {
        $request = $this->v1RegisterRequest($register_request, $fields_users, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Register200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Register200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1RegisterAsync
     *
     * @param  \LifeHub\ApiClient\Model\RegisterRequest $register_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Register'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1RegisterAsync($register_request, $fields_users = null, string $contentType = self::contentTypes['v1Register'][0])
    {
        return $this->v1RegisterAsyncWithHttpInfo($register_request, $fields_users, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1RegisterAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\RegisterRequest $register_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Register'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1RegisterAsyncWithHttpInfo($register_request, $fields_users = null, string $contentType = self::contentTypes['v1Register'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Register200Response';
        $request = $this->v1RegisterRequest($register_request, $fields_users, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Register'
     *
     * @param  \LifeHub\ApiClient\Model\RegisterRequest $register_request (required)
     * @param  string[]|null $fields_users (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Register'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1RegisterRequest($register_request, $fields_users = null, string $contentType = self::contentTypes['v1Register'][0])
    {

        // verify the required parameter 'register_request' is set
        if ($register_request === null || (is_array($register_request) && count($register_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $register_request when calling v1Register'
            );
        }



        $resourcePath = '/v1/register';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_users,
            'fields[users]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($register_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($register_request));
            } else {
                $httpBody = $register_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
