<?php
/**
 * GlobalSearchApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LifeHub\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LifeHub\ApiClient\ApiException;
use LifeHub\ApiClient\Configuration;
use LifeHub\ApiClient\FormDataProcessor;
use LifeHub\ApiClient\HeaderSelector;
use LifeHub\ApiClient\ObjectSerializer;

/**
 * GlobalSearchApi Class Doc Comment
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GlobalSearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1Search' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1Search
     *
     * @param  string $q q (required)
     * @param  int|null $limit limit (optional)
     * @param  string|null $module module (optional)
     * @param  string|null $entity_type entity_type (optional)
     * @param  bool|null $is_private is_private (optional)
     * @param  bool|null $is_archived is_archived (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Search'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1Search200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject|\LifeHub\ApiClient\Model\InlineObject1
     */
    public function v1Search($q, $limit = null, $module = null, $entity_type = null, $is_private = null, $is_archived = null, string $contentType = self::contentTypes['v1Search'][0])
    {
        list($response) = $this->v1SearchWithHttpInfo($q, $limit, $module, $entity_type, $is_private, $is_archived, $contentType);
        return $response;
    }

    /**
     * Operation v1SearchWithHttpInfo
     *
     * @param  string $q (required)
     * @param  int|null $limit (optional)
     * @param  string|null $module (optional)
     * @param  string|null $entity_type (optional)
     * @param  bool|null $is_private (optional)
     * @param  bool|null $is_archived (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Search'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1Search200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject|\LifeHub\ApiClient\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SearchWithHttpInfo($q, $limit = null, $module = null, $entity_type = null, $is_private = null, $is_archived = null, string $contentType = self::contentTypes['v1Search'][0])
    {
        $request = $this->v1SearchRequest($q, $limit, $module, $entity_type, $is_private, $is_archived, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1Search200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1Search200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1Search200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1SearchAsync
     *
     * @param  string $q (required)
     * @param  int|null $limit (optional)
     * @param  string|null $module (optional)
     * @param  string|null $entity_type (optional)
     * @param  bool|null $is_private (optional)
     * @param  bool|null $is_archived (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchAsync($q, $limit = null, $module = null, $entity_type = null, $is_private = null, $is_archived = null, string $contentType = self::contentTypes['v1Search'][0])
    {
        return $this->v1SearchAsyncWithHttpInfo($q, $limit, $module, $entity_type, $is_private, $is_archived, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SearchAsyncWithHttpInfo
     *
     * @param  string $q (required)
     * @param  int|null $limit (optional)
     * @param  string|null $module (optional)
     * @param  string|null $entity_type (optional)
     * @param  bool|null $is_private (optional)
     * @param  bool|null $is_archived (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchAsyncWithHttpInfo($q, $limit = null, $module = null, $entity_type = null, $is_private = null, $is_archived = null, string $contentType = self::contentTypes['v1Search'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1Search200Response';
        $request = $this->v1SearchRequest($q, $limit, $module, $entity_type, $is_private, $is_archived, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Search'
     *
     * @param  string $q (required)
     * @param  int|null $limit (optional)
     * @param  string|null $module (optional)
     * @param  string|null $entity_type (optional)
     * @param  bool|null $is_private (optional)
     * @param  bool|null $is_archived (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1SearchRequest($q, $limit = null, $module = null, $entity_type = null, $is_private = null, $is_archived = null, string $contentType = self::contentTypes['v1Search'][0])
    {

        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling v1Search'
            );
        }
        if (strlen($q) > 2000) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling GlobalSearchApi.v1Search, must be smaller than or equal to 2000.');
        }
        if (strlen($q) < 1) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling GlobalSearchApi.v1Search, must be bigger than or equal to 1.');
        }
        
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling GlobalSearchApi.v1Search, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling GlobalSearchApi.v1Search, must be bigger than or equal to 1.');
        }
        
        if ($module !== null && strlen($module) > 255) {
            throw new \InvalidArgumentException('invalid length for "$module" when calling GlobalSearchApi.v1Search, must be smaller than or equal to 255.');
        }
        
        if ($entity_type !== null && strlen($entity_type) > 255) {
            throw new \InvalidArgumentException('invalid length for "$entity_type" when calling GlobalSearchApi.v1Search, must be smaller than or equal to 255.');
        }
        



        $resourcePath = '/v1/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $module,
            'module', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $entity_type,
            'entity_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $is_private,
            'is_private', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $is_archived,
            'is_archived', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
