<?php
/**
 * SearchHistoryApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LifeHub\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LifeHub\ApiClient\ApiException;
use LifeHub\ApiClient\Configuration;
use LifeHub\ApiClient\FormDataProcessor;
use LifeHub\ApiClient\HeaderSelector;
use LifeHub\ApiClient\ObjectSerializer;

/**
 * SearchHistoryApi Class Doc Comment
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchHistoryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1SearchHistoryDestroy' => [
            'application/json',
        ],
        'v1SearchHistoryStore' => [
            'application/json',
        ],
        'v1SearchTerms' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1SearchHistoryDestroy
     *
     * @param  int $search_history The search history ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryDestroy'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1SearchHistoryDestroy($search_history, string $contentType = self::contentTypes['v1SearchHistoryDestroy'][0])
    {
        $this->v1SearchHistoryDestroyWithHttpInfo($search_history, $contentType);
    }

    /**
     * Operation v1SearchHistoryDestroyWithHttpInfo
     *
     * @param  int $search_history The search history ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryDestroy'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SearchHistoryDestroyWithHttpInfo($search_history, string $contentType = self::contentTypes['v1SearchHistoryDestroy'][0])
    {
        $request = $this->v1SearchHistoryDestroyRequest($search_history, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1SearchHistoryDestroyAsync
     *
     * @param  int $search_history The search history ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchHistoryDestroyAsync($search_history, string $contentType = self::contentTypes['v1SearchHistoryDestroy'][0])
    {
        return $this->v1SearchHistoryDestroyAsyncWithHttpInfo($search_history, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SearchHistoryDestroyAsyncWithHttpInfo
     *
     * @param  int $search_history The search history ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchHistoryDestroyAsyncWithHttpInfo($search_history, string $contentType = self::contentTypes['v1SearchHistoryDestroy'][0])
    {
        $returnType = '';
        $request = $this->v1SearchHistoryDestroyRequest($search_history, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SearchHistoryDestroy'
     *
     * @param  int $search_history The search history ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1SearchHistoryDestroyRequest($search_history, string $contentType = self::contentTypes['v1SearchHistoryDestroy'][0])
    {

        // verify the required parameter 'search_history' is set
        if ($search_history === null || (is_array($search_history) && count($search_history) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search_history when calling v1SearchHistoryDestroy'
            );
        }


        $resourcePath = '/v1/search/history/{searchHistory}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($search_history !== null) {
            $resourcePath = str_replace(
                '{searchHistory}',
                ObjectSerializer::toPathValue($search_history),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SearchHistoryStore
     *
     * @param  \LifeHub\ApiClient\Model\SearchHistoryCreateRequest $search_history_create_request search_history_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryStore'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1SearchHistoryStore201Response|\LifeHub\ApiClient\Model\V1DashboardPinsStore400Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1SearchHistoryStore($search_history_create_request, string $contentType = self::contentTypes['v1SearchHistoryStore'][0])
    {
        list($response) = $this->v1SearchHistoryStoreWithHttpInfo($search_history_create_request, $contentType);
        return $response;
    }

    /**
     * Operation v1SearchHistoryStoreWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\SearchHistoryCreateRequest $search_history_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryStore'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1SearchHistoryStore201Response|\LifeHub\ApiClient\Model\V1DashboardPinsStore400Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SearchHistoryStoreWithHttpInfo($search_history_create_request, string $contentType = self::contentTypes['v1SearchHistoryStore'][0])
    {
        $request = $this->v1SearchHistoryStoreRequest($search_history_create_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1SearchHistoryStore201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1DashboardPinsStore400Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1SearchHistoryStore201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1SearchHistoryStore201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1DashboardPinsStore400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1SearchHistoryStoreAsync
     *
     * @param  \LifeHub\ApiClient\Model\SearchHistoryCreateRequest $search_history_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchHistoryStoreAsync($search_history_create_request, string $contentType = self::contentTypes['v1SearchHistoryStore'][0])
    {
        return $this->v1SearchHistoryStoreAsyncWithHttpInfo($search_history_create_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SearchHistoryStoreAsyncWithHttpInfo
     *
     * @param  \LifeHub\ApiClient\Model\SearchHistoryCreateRequest $search_history_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchHistoryStoreAsyncWithHttpInfo($search_history_create_request, string $contentType = self::contentTypes['v1SearchHistoryStore'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1SearchHistoryStore201Response';
        $request = $this->v1SearchHistoryStoreRequest($search_history_create_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SearchHistoryStore'
     *
     * @param  \LifeHub\ApiClient\Model\SearchHistoryCreateRequest $search_history_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchHistoryStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1SearchHistoryStoreRequest($search_history_create_request, string $contentType = self::contentTypes['v1SearchHistoryStore'][0])
    {

        // verify the required parameter 'search_history_create_request' is set
        if ($search_history_create_request === null || (is_array($search_history_create_request) && count($search_history_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search_history_create_request when calling v1SearchHistoryStore'
            );
        }


        $resourcePath = '/v1/search/history';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($search_history_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($search_history_create_request));
            } else {
                $httpBody = $search_history_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SearchTerms
     *
     * @param  string $module module (required)
     * @param  string $type type (required)
     * @param  string $term term (required)
     * @param  string[]|null $fields_search_histories fields_search_histories (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchTerms'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1SearchTerms200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject
     */
    public function v1SearchTerms($module, $type, $term, $fields_search_histories = null, string $contentType = self::contentTypes['v1SearchTerms'][0])
    {
        list($response) = $this->v1SearchTermsWithHttpInfo($module, $type, $term, $fields_search_histories, $contentType);
        return $response;
    }

    /**
     * Operation v1SearchTermsWithHttpInfo
     *
     * @param  string $module (required)
     * @param  string $type (required)
     * @param  string $term (required)
     * @param  string[]|null $fields_search_histories (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchTerms'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1SearchTerms200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SearchTermsWithHttpInfo($module, $type, $term, $fields_search_histories = null, string $contentType = self::contentTypes['v1SearchTerms'][0])
    {
        $request = $this->v1SearchTermsRequest($module, $type, $term, $fields_search_histories, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1SearchTerms200Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1SearchTerms200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1SearchTerms200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1SearchTermsAsync
     *
     * @param  string $module (required)
     * @param  string $type (required)
     * @param  string $term (required)
     * @param  string[]|null $fields_search_histories (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchTerms'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchTermsAsync($module, $type, $term, $fields_search_histories = null, string $contentType = self::contentTypes['v1SearchTerms'][0])
    {
        return $this->v1SearchTermsAsyncWithHttpInfo($module, $type, $term, $fields_search_histories, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SearchTermsAsyncWithHttpInfo
     *
     * @param  string $module (required)
     * @param  string $type (required)
     * @param  string $term (required)
     * @param  string[]|null $fields_search_histories (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchTerms'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SearchTermsAsyncWithHttpInfo($module, $type, $term, $fields_search_histories = null, string $contentType = self::contentTypes['v1SearchTerms'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1SearchTerms200Response';
        $request = $this->v1SearchTermsRequest($module, $type, $term, $fields_search_histories, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SearchTerms'
     *
     * @param  string $module (required)
     * @param  string $type (required)
     * @param  string $term (required)
     * @param  string[]|null $fields_search_histories (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1SearchTerms'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1SearchTermsRequest($module, $type, $term, $fields_search_histories = null, string $contentType = self::contentTypes['v1SearchTerms'][0])
    {

        // verify the required parameter 'module' is set
        if ($module === null || (is_array($module) && count($module) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $module when calling v1SearchTerms'
            );
        }

        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling v1SearchTerms'
            );
        }

        // verify the required parameter 'term' is set
        if ($term === null || (is_array($term) && count($term) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term when calling v1SearchTerms'
            );
        }



        $resourcePath = '/v1/search/terms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $module,
            'module', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $term,
            'term', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_search_histories,
            'fields[search_histories]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
