<?php
/**
 * UserAiModelApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LifeHub
 *
 * API for the Personal Everything App
 *
 * The version of the OpenAPI document: 0.1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LifeHub\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LifeHub\ApiClient\ApiException;
use LifeHub\ApiClient\Configuration;
use LifeHub\ApiClient\FormDataProcessor;
use LifeHub\ApiClient\HeaderSelector;
use LifeHub\ApiClient\ObjectSerializer;

/**
 * UserAiModelApi Class Doc Comment
 *
 * @category Class
 * @package  LifeHub\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserAiModelApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AiModelsDestroy' => [
            'application/json',
        ],
        'v1AiModelsShow' => [
            'application/json',
        ],
        'v1AiModelsUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AiModelsDestroy
     *
     * @param  int $model The model ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsDestroy'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1AiModelsDestroy($model, string $contentType = self::contentTypes['v1AiModelsDestroy'][0])
    {
        $this->v1AiModelsDestroyWithHttpInfo($model, $contentType);
    }

    /**
     * Operation v1AiModelsDestroyWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsDestroy'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AiModelsDestroyWithHttpInfo($model, string $contentType = self::contentTypes['v1AiModelsDestroy'][0])
    {
        $request = $this->v1AiModelsDestroyRequest($model, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AiModelsDestroyAsync
     *
     * @param  int $model The model ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsDestroyAsync($model, string $contentType = self::contentTypes['v1AiModelsDestroy'][0])
    {
        return $this->v1AiModelsDestroyAsyncWithHttpInfo($model, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AiModelsDestroyAsyncWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsDestroyAsyncWithHttpInfo($model, string $contentType = self::contentTypes['v1AiModelsDestroy'][0])
    {
        $returnType = '';
        $request = $this->v1AiModelsDestroyRequest($model, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AiModelsDestroy'
     *
     * @param  int $model The model ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AiModelsDestroyRequest($model, string $contentType = self::contentTypes['v1AiModelsDestroy'][0])
    {

        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling v1AiModelsDestroy'
            );
        }


        $resourcePath = '/v1/ai/models/{model}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($model !== null) {
            $resourcePath = str_replace(
                '{model}',
                ObjectSerializer::toPathValue($model),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AiModelsShow
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models fields_user_ai_models (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsShow'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1AiModelsShow200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1
     */
    public function v1AiModelsShow($model, $fields_user_ai_models = null, string $contentType = self::contentTypes['v1AiModelsShow'][0])
    {
        list($response) = $this->v1AiModelsShowWithHttpInfo($model, $fields_user_ai_models, $contentType);
        return $response;
    }

    /**
     * Operation v1AiModelsShowWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsShow'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1AiModelsShow200Response|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AiModelsShowWithHttpInfo($model, $fields_user_ai_models = null, string $contentType = self::contentTypes['v1AiModelsShow'][0])
    {
        $request = $this->v1AiModelsShowRequest($model, $fields_user_ai_models, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AiModelsShowAsync
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsShowAsync($model, $fields_user_ai_models = null, string $contentType = self::contentTypes['v1AiModelsShow'][0])
    {
        return $this->v1AiModelsShowAsyncWithHttpInfo($model, $fields_user_ai_models, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AiModelsShowAsyncWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsShowAsyncWithHttpInfo($model, $fields_user_ai_models = null, string $contentType = self::contentTypes['v1AiModelsShow'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1AiModelsShow200Response';
        $request = $this->v1AiModelsShowRequest($model, $fields_user_ai_models, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AiModelsShow'
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AiModelsShowRequest($model, $fields_user_ai_models = null, string $contentType = self::contentTypes['v1AiModelsShow'][0])
    {

        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling v1AiModelsShow'
            );
        }



        $resourcePath = '/v1/ai/models/{model}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_user_ai_models,
            'fields[user_ai_models]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($model !== null) {
            $resourcePath = str_replace(
                '{model}',
                ObjectSerializer::toPathValue($model),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AiModelsUpdate
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models fields_user_ai_models (optional)
     * @param  \LifeHub\ApiClient\Model\UserAiModelUpdateRequest|null $user_ai_model_update_request user_ai_model_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsUpdate'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LifeHub\ApiClient\Model\V1AiModelsShow200Response|\LifeHub\ApiClient\Model\InlineObject|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1
     */
    public function v1AiModelsUpdate($model, $fields_user_ai_models = null, $user_ai_model_update_request = null, string $contentType = self::contentTypes['v1AiModelsUpdate'][0])
    {
        list($response) = $this->v1AiModelsUpdateWithHttpInfo($model, $fields_user_ai_models, $user_ai_model_update_request, $contentType);
        return $response;
    }

    /**
     * Operation v1AiModelsUpdateWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  \LifeHub\ApiClient\Model\UserAiModelUpdateRequest|null $user_ai_model_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsUpdate'] to see the possible values for this operation
     *
     * @throws \LifeHub\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LifeHub\ApiClient\Model\V1AiModelsShow200Response|\LifeHub\ApiClient\Model\InlineObject|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1|\LifeHub\ApiClient\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AiModelsUpdateWithHttpInfo($model, $fields_user_ai_models = null, $user_ai_model_update_request = null, string $contentType = self::contentTypes['v1AiModelsUpdate'][0])
    {
        $request = $this->v1AiModelsUpdateRequest($model, $fields_user_ai_models, $user_ai_model_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\V1AiModelsShow200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LifeHub\ApiClient\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AiModelsUpdateAsync
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  \LifeHub\ApiClient\Model\UserAiModelUpdateRequest|null $user_ai_model_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsUpdateAsync($model, $fields_user_ai_models = null, $user_ai_model_update_request = null, string $contentType = self::contentTypes['v1AiModelsUpdate'][0])
    {
        return $this->v1AiModelsUpdateAsyncWithHttpInfo($model, $fields_user_ai_models, $user_ai_model_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AiModelsUpdateAsyncWithHttpInfo
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  \LifeHub\ApiClient\Model\UserAiModelUpdateRequest|null $user_ai_model_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AiModelsUpdateAsyncWithHttpInfo($model, $fields_user_ai_models = null, $user_ai_model_update_request = null, string $contentType = self::contentTypes['v1AiModelsUpdate'][0])
    {
        $returnType = '\LifeHub\ApiClient\Model\V1AiModelsShow200Response';
        $request = $this->v1AiModelsUpdateRequest($model, $fields_user_ai_models, $user_ai_model_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AiModelsUpdate'
     *
     * @param  int $model The model ID (required)
     * @param  string[]|null $fields_user_ai_models (optional)
     * @param  \LifeHub\ApiClient\Model\UserAiModelUpdateRequest|null $user_ai_model_update_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AiModelsUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AiModelsUpdateRequest($model, $fields_user_ai_models = null, $user_ai_model_update_request = null, string $contentType = self::contentTypes['v1AiModelsUpdate'][0])
    {

        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling v1AiModelsUpdate'
            );
        }




        $resourcePath = '/v1/ai/models/{model}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields_user_ai_models,
            'fields[user_ai_models]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($model !== null) {
            $resourcePath = str_replace(
                '{model}',
                ObjectSerializer::toPathValue($model),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_ai_model_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_ai_model_update_request));
            } else {
                $httpBody = $user_ai_model_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
