services:
  cache:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - project_network
    volumes:
      - cache:/data

  typesense:
    image: typesense/typesense:30.1
    container_name: typesense
    restart: unless-stopped
    command: '--data-dir /data --api-key=xyz'
    ports:
      - "8108:8108"
    volumes:
      - search:/data
    networks:
      - project_network

  database:
    image: pgvector/pgvector:pg17
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - project_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ui:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  cache:
  database:
  search:
  ui:
